service: weather-clock-server

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    NODE_ENV: ${opt:stage}

package:
  include:
    - src/**
    - src/config/environment/${opt:stage}.js
  exclude:
    - "**/*.test.js"
    - src/config/environment/*.js

functions:
  layers:
    handler: src/app/layers.handle
    events:
      - http:
          path: layers
          method: get
          cors: true
