service: weather-clock-server

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x

package:
  include:
    - src/**
  exclude:
    - "**/*.test.js"

functions:
  configuration:
    handler: src/app/configuration.handle
    events:
      - http:
          path: configuration
          method: get
          cors: true
